# This is a basic workflow to help you get started with Actions
name: Testing CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: testing

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install npm packages
        run: npm install

      - name: Install nwb globally
        run: npm install nwb -g

      - name: Create .env file
        run: |
          touch .env
          echo NODE_ENV=${{ secrets.NODE_ENV }} >> .env
          echo MAPBOX_USER=${{ secrets.MAPBOX_USER }} >> .env
          echo MAPBOX_API_TOKEN=${{ secrets.MAPBOX_API_TOKEN }} >> .env
          echo AWS_ENDPOINT=${{ secrets.AWS_ENDPOINT }} >> .env
          cat .env

      - name: Run nwb build
        run: nwb build-react-component --copy-files

      - name: Deploy 🚀
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: demo/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
